const modInfo = `{
    "acadYear": "2023/2024",
    "preclusion": "If undertaking an Undergraduate Degree THEN ( must not have completed 1 of CS1010/CS1010A/CS1010E/CS1010J/CS1010S/CS1010X at a grade of at least D)",
    "preclusionRule": "PROGRAM_TYPES IF_IN Undergraduate Degree THEN (COURSES (1) CS1010:D, CS1010J:D, CS1010S:D, CS1010E:D, CS1010X:D, CS1010A:D)",
    "description": "This course introduces the concepts of programming and computational problem solving, and is the first and foremost introductory course to computing. Starting from a small core of fundamental abstractions, the course introduces programming as a method for communicating computational processes. The course begins with purely functional programming based on a simple substitution-based execution model, and ends with a powerful modern imperative language based on a realistic environment-based execution model. Topics covered include: functional abstraction, recursion, higher-order functions, data abstraction, algorithmic strategies, state mutation, loops and arrays, evaluation strategies, sorting and searching, debugging and testing.",
    "title": "Programming Methodology",
    "additionalInformation": "",
    "department": "Computer Science",
    "faculty": "Computing",
    "workload": [
      2,
      2,
      1,
      3,
      2
    ],
    "gradingBasisDescription": "Graded",
    "moduleCredit": "4",
    "moduleCode": "CS1101S",
    "attributes": {
      "mpes1": true,
      "mpes2": true,
      "su": true
    },
    "semesterData": [
      {
        "semester": 1,
        "timetable": [
          {
            "classNo": "16E",
            "startTime": "1600",
            "endTime": "1700",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "I3-0338",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "18E",
            "startTime": "1800",
            "endTime": "1900",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "I3-0339",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "16B",
            "startTime": "1600",
            "endTime": "1700",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "09C",
            "startTime": "0900",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "18D",
            "startTime": "1800",
            "endTime": "1900",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "15B",
            "startTime": "1500",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "05F",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09D",
            "startTime": "0900",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "06K",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07D",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08H",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09A",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07M",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06B",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06G",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09F",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01B",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01E",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01G",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02J",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02K",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03A",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03K",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04B",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "11B",
            "startTime": "1100",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "10D",
            "startTime": "1000",
            "endTime": "1100",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "07C",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08A",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08B",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08K",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06A",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09D",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02A",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02C",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02L",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03F",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04D",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04J",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05D",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "15D",
            "startTime": "1500",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "02B",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03B",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03D",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03M",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04E",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05J",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "14B",
            "startTime": "1400",
            "endTime": "1500",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "14A",
            "startTime": "1400",
            "endTime": "1500",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "06E",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "16C",
            "startTime": "1600",
            "endTime": "1700",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "17A",
            "startTime": "1700",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "18A",
            "startTime": "1800",
            "endTime": "1900",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "10A",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10C",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07J",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07H",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07E",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "14D",
            "startTime": "1400",
            "endTime": "1500",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "17B",
            "startTime": "1700",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "15C",
            "startTime": "1500",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "11A",
            "startTime": "1100",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "10K",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10H",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08D",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01D",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01F",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02H",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02M",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03E",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04A",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05A",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10B",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07F",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01K",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01H",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02D",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04C",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05G",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01A",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04F",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04H",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05C",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05E",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09A",
            "startTime": "0900",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "11C",
            "startTime": "1100",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "10F",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05K",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09B",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02F",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09B",
            "startTime": "0900",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "10G",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07A",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08F",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10E",
            "startTime": "1000",
            "endTime": "1100",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "I3-0339",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "09E",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01J",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10M",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09C",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09J",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03H",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03J",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05H",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "15A",
            "startTime": "1500",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "14C",
            "startTime": "1400",
            "endTime": "1500",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "07B",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "17D",
            "startTime": "1700",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "17C",
            "startTime": "1700",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "08C",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08J",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07K",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01M",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "18C",
            "startTime": "1800",
            "endTime": "1900",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "09H",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04G",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02G",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03C",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04M",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06M",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08G",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08M",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09G",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "02E",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "1",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "E-Learn_C",
            "day": "Friday",
            "lessonType": "Lecture",
            "size": 850,
            "covidZone": "Unknown"
          },
          {
            "classNo": "01C",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05B",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "11E",
            "startTime": "1100",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "I3-0339",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "06J",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10D",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08E",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06C",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05L",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04L",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "16D",
            "startTime": "1600",
            "endTime": "1700",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "10A",
            "startTime": "1000",
            "endTime": "1100",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "11D",
            "startTime": "1100",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "14E",
            "startTime": "1400",
            "endTime": "1500",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "I3-0339",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "10J",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10L",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "08L",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "18B",
            "startTime": "1800",
            "endTime": "1900",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "07L",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "01L",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "05M",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06L",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "07G",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10C",
            "startTime": "1000",
            "endTime": "1100",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-25",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "10E",
            "startTime": "1600",
            "endTime": "1800",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "06H",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "03G",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "16A",
            "startTime": "1600",
            "endTime": "1700",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM4-02-02",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "03L",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "04K",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "15E",
            "startTime": "1500",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "I3-0339",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "B"
          },
          {
            "classNo": "09L",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "1",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "E-Learn_C",
            "day": "Wednesday",
            "lessonType": "Lecture",
            "size": 850,
            "covidZone": "Unknown"
          },
          {
            "classNo": "06F",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-20",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09M",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "09K",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0201",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          },
          {
            "classNo": "10B",
            "startTime": "1000",
            "endTime": "1100",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-01-22",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 24,
            "covidZone": "Unknown"
          },
          {
            "classNo": "06D",
            "startTime": "0800",
            "endTime": "1000",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0210",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "B"
          }
        ],
        "covidZones": [
          "B",
          "Unknown"
        ],
        "examDate": "2023-11-27T05:00:00.000Z",
        "examDuration": 120
      },
      {
        "semester": 2,
        "timetable": [
          {
            "classNo": "05",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Monday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "Unknown"
          },
          {
            "classNo": "04",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "Unknown"
          },
          {
            "classNo": "06",
            "startTime": "1400",
            "endTime": "1600",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "Unknown"
          },
          {
            "classNo": "1",
            "startTime": "1200",
            "endTime": "1400",
            "weeks": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM1-0212",
            "day": "Wednesday",
            "lessonType": "Lecture",
            "size": 40,
            "covidZone": "B"
          },
          {
            "classNo": "02",
            "startTime": "1100",
            "endTime": "1200",
            "weeks": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 20,
            "covidZone": "Unknown"
          },
          {
            "classNo": "01",
            "startTime": "1000",
            "endTime": "1100",
            "weeks": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Thursday",
            "lessonType": "Recitation",
            "size": 20,
            "covidZone": "Unknown"
          },
          {
            "classNo": "02",
            "startTime": "1000",
            "endTime": "1200",
            "weeks": [
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            "venue": "COM3-B1-10",
            "day": "Tuesday",
            "lessonType": "Tutorial",
            "size": 8,
            "covidZone": "Unknown"
          }
        ],
        "covidZones": [
          "Unknown",
          "B"
        ],
        "examDate": "2024-04-30T05:00:00.000Z",
        "examDuration": 120
      }
    ],
    "fulfillRequirements": [
      "FIN4719",
      "CP2106",
      "CS2100",
      "IT2001",
      "IT2002",
      "CS2107",
      "CS2100R",
      "CS2040C",
      "CS2040",
      "CS2030",
      "CS3237",
      "IT3011",
      "CS2040S",
      "CS2030S",
      "IS3221",
      "IS4241",
      "BT4212",
      "BT4221",
      "BT4222",
      "BT2102",
      "IT3010",
      "BT3017",
      "EE5907",
      "QF3101",
      "NST2056"
    ]
  }
  `