# 应用服务 WEB 访问端口
server.port=8080

# 数据库连接信息
spring.datasource.url=jdbc:mariadb://47.116.173.60:3306/nusplannerAPI?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=your_password

# MyBatis中xml文件映射的位置
mybatis.mapper-locations=classpath:mappers/*.xml

# 设置全局日志级别:WARN
logging.level.root=WARN
# 设置局部日志级别:DEBUG
logging.level.cn.tedu.nusplannerAPI=DEBUG

# 自动识别表字段名与属性名命名方式不一样的问题  parentId与 parent_id
mybatis.configuration.map-underscore-to-camel-case=true

# 设置单个上传文件大小
spring.servlet.multipart.max-file-size=100MB
# 设置多个上传文件大小
spring.servlet.multipart.max-request-size=500MB

# 设置d:/files与后端static均为静态资源文件夹 快捷方式swrs
# file:表示这是文件系统中的磁盘路径
spring.web.resources.static-locations=file:/Users/zhangyuhao/Documents/Zoom,classpath:static

